### PR TITLE
Enable WiFiUDP for Beken-72XX

### PR DESCRIPTION
**Pull request by lonerzzz**
As the title says, one-liner

### CODE REVIEW

**Comment by mrmultifunk** [comment]
Hello, i'm need this in my configuration aswell. Is there a way to add this manually? Thanks!

**Comment by kuba2k2** [comment]
Yes, you can just modify the file that this PR changes.

**Comment by mrmultifunk** [comment]
Thanks, that did the trick.

**Comment by kuba2k2** [comment]
The fix has now been included in the merged refactor PR - so I'm closing this.

**Pull request closed without merging**
